
atlas {
  cloudwatch {

    // https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/observability-gateway-metrics.html
    agentcore-gateway = {
      namespace = "AWS/Bedrock-AgentCore"
      period = 1m
      end-period-offset = 5

      dimensions = [
        "Operation",
        "Name",
        "Resource"
      ]

      metrics = [
        {
          name = "Invocations"
          alias = "aws.agentcore.invocations"
          conversion = "sum,rate"
        },
        {
          name = "Throttles"
          alias = "aws.agentcore.throttles"
          conversion = "sum,rate"
        },
        {
          name = "SystemErrors"
          alias = "aws.agentcore.systemErrors"
          conversion = "sum,rate"
        },
        {
          name = "UserErrors"
          alias = "aws.agentcore.userErrors"
          conversion = "sum,rate"
        },
        {
          name = "Latency"
          alias = "aws.agentcore.latency"
          conversion = "timer-millis"
        },
        {
          name = "Duration"
          alias = "aws.agentcore.duration"
          conversion = "timer-millis"
        },
        {
          name = "TargetExecutionTime"
          alias = "aws.agentcore.targetExecutionTime"
          conversion = "timer-millis"
        }
      ]
    }

    agentcore-runtime = {
      namespace = "AWS/Bedrock-AgentCore"
      period = 1m
      end-period-offset = 5

      dimensions = [
        "Service",
        "Resource"
      ]

      metrics = [
        {
          name = "Invocations"
          alias = "aws.agentcore.invocations"
          conversion = "sum,rate"
        },
        {
          name = "Throttles"
          alias = "aws.agentcore.throttles"
          conversion = "sum,rate"
        },
        {
          name = "SystemErrors"
          alias = "aws.agentcore.systemErrors"
          conversion = "sum,rate"
        },
        {
          name = "Sessions"
          alias = "aws.agentcore.sessions"
          conversion = "sum,rate"
        },
        {
          name = "InboundStreamingBytesProcessed"
          alias = "aws.agentcore.bytesProcessed"
          conversion = "sum,rate"
          tags = [
            {
              key = "id"
              value = "in"
            }
          ]
        },
        {
          name = "OutboundStreamingBytesProcessed"
          alias = "aws.agentcore.bytesProcessed"
          conversion = "sum,rate"
          tags = [
            {
              key = "id"
              value = "out"
            }
          ]
        },
        {
          name = "UserErrors"
          alias = "aws.agentcore.userErrors"
          conversion = "sum,rate"
        },
        {
          name = "Latency"
          alias = "aws.agentcore.latency"
          conversion = "timer-millis"
        },
        {
          name = "Duration"
          alias = "aws.agentcore.duration"
          conversion = "timer-millis"
        },
        {
          name = "CPUUsed-vCPUHours"
          alias = "aws.agentcore.cpuUsed"
          conversion = "max"
        },
        {
          name = "MemoryUsed-GBHours"
          alias = "aws.agentcore.memoryUsed"
          conversion = "max"
        }
      ]
    }
  }
}
