
atlas {
  cloudwatch {

    // https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/programming-cloudwatch-metrics.html
    cloudfront = {
      namespace = "AWS/CloudFront"
      period = 1m
      end-period-offset = 5

      dimensions = [
        "DistributionId",
        "Region"
      ]

      metrics = [
        {
          name = "4xxErrorRate"
          alias = "aws.cloudfront.4xxErrorRate"
          conversion = "max,percent"
        },
        {
          name = "5xxErrorRate"
          alias = "aws.cloudfront.5xxErrorRate"
          conversion = "max,percent"
        },
        {
          name = "OriginLatency"
          alias = "aws.cloudfront.originLatency"
          conversion = "timer-millis"
        },
        {
          name = "Requests"
          alias = "aws.cloudfront.requests"
          conversion = "sum,rate"
        },
        {
          name = "TotalErrorRate"
          alias = "aws.cloudfront.totalErrorRate"
          conversion = "max,percent"
        }
      ]
    }
  }
}
