
atlas {
  cloudwatch {

    // DDoS protection metrics for resources protected by AWS Shield Advanced.
    // https://docs.aws.amazon.com/shield/latest/developerguide/monitoring-cloudwatch.html
    ddos = {
      namespace = "AWS/DDoSProtection"
      period = 1m
      end-period-offset = 9

      dimensions = [
        "ResourceArn"
      ]

      metrics = [
        {
          name = "DDoSDetected"
          alias = "aws.ddos.detected"
          conversion = "max"
        },
      ]
    }

    // DDoS attack metrics broken down by attack vector.
    // https://docs.aws.amazon.com/shield/latest/developerguide/monitoring-cloudwatch.html
    ddos-attack = {
      namespace = "AWS/DDoSProtection"
      period = 1m
      end-period-offset = 9

      dimensions = [
        "ResourceArn",
        "AttackVector"
      ]

      metrics = [
        {
          name = "DDoSAttackBitsPerSecond"
          alias = "aws.ddos.attackBitsPerSecond"
          conversion = "max"
        },
        {
          name = "DDoSAttackPacketsPerSecond"
          alias = "aws.ddos.attackPacketsPerSecond"
          conversion = "max"
        },
        {
          name = "DDoSAttackRequestsPerSecond"
          alias = "aws.ddos.attackRequestsPerSecond"
          conversion = "max"
        },
      ]
    }
  }
}
