
atlas {
  cloudwatch {

    // https://docs.aws.amazon.com/eks/latest/userguide/cloudwatch.html
    eks-api = {
      namespace = "AWS/EKS"
      period = 1m
      end-period-offset = 9

      dimensions = [
        "ClusterName"
      ]

      metrics = [
        {
          name = "apiserver_request_total"
          alias = "aws.eks.requestTotal"
          conversion = "sum,rate"
          tags = []
        },
        {
          name = "apiserver_request_total_4XX"
          alias = "aws.eks.requestTotal4xx"
          conversion = "sum,rate"
        },
        {
          name = "apiserver_request_total_429"
          alias = "aws.eks.requestTotal429"
          conversion = "sum,rate"
        },
        {
          name = "apiserver_request_total_5XX"
          alias = "aws.eks.requestTotal5xx"
          conversion = "sum,rate"
        },
        {
          name = "apiserver_request_total_LIST_PODS"
          alias = "aws.efs.requestTotalListPods"
          conversion = "sum,rate"
        }
      ]
    }
  }
}