
atlas {
  cloudwatch {

    // https://docs.aws.amazon.com/vpc/latest/ipam/cloudwatch-ipam-ip-address-usage.html#cloudwatch-ipam-prefix-list-resolver-metrics
    ipam-prefix-list-resolver-sync = {
      namespace = "AWS/IPAM"
      period = 5m
      end-period-offset = 5

      dimensions = [
        "IpamPrefixListResolverId",
        "IpamPrefixListResolverTargetId"
      ]

      metrics = [
        {
          name = "IpamPrefixListResolverSyncSuccess"
          alias = "aws.ipam.prefixListResolverSyncSuccess"
          conversion = "sum,rate"
        },
        {
          name = "IpamPrefixListResolverSyncFailure"
          alias = "aws.ipam.prefixListResolverSyncFailure"
          conversion = "sum,rate"
        }
      ]
    }

    ipam-prefix-list-resolver-version = {
      namespace = "AWS/IPAM"
      period = 5m
      end-period-offset = 5

      dimensions = [
        "IpamPrefixListResolverId"
      ]

      metrics = [
        {
          name = "IpamPrefixListResolverVersionCreationSuccess"
          alias = "aws.ipam.prefixListResolverVersionCreationSuccess"
          conversion = "sum,rate"
        },
        {
          name = "IpamPrefixListResolverVersionCreationFailure"
          alias = "aws.ipam.prefixListResolverVersionCreationFailure"
          conversion = "sum,rate"
        }
      ]
    }
  }
}
