atlas {
  cloudwatch {

    # https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch-Logs-Monitoring-CloudWatch-Metrics.html
    cw-logs = {
      namespace = "AWS/Logs"
      period = 1m
      end-period-offset = 3

      dimensions = [
        "FilterName",
        "LogGroupName",
        "DestinationType"
      ]

      metrics = [
        {
          name = "ForwardedBytes"
          alias = "aws.cw.logs.forwardedBytes"
          conversion = "sum,rate"
        },
        {
          name = "ForwardedLogEvents"
          alias = "aws.cw.logs.forwardedLogEvents"
          conversion = "sum,rate"
        },
        {
          name = "DeliveryErrors"
          alias = "aws.cw.logs.deliveryErrors"
          conversion = "sum,rate"
        },
        {
          name = "DeliveryThrottling"
          alias = "aws.cw.logs.deliveryThrottling"
          conversion = "sum,rate"
        }
      ]
    }
  }
}